# kustomize/overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../helm/app
transformers:
  - prod.yaml  # Contains production-specific config overrides
